# Konfigurasi NGINX untuk Frontend (Web App)
server {
    listen 80;
    server_name asset.digdaya.net;

    location / {
        proxy_pass http://localhost:20080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Konfigurasi NGINX untuk Backend (API)
server {
    listen 80;
    server_name api.digdaya.net;

    # Mengarahkan prefix /asset/v1/ ke container backend (port 21080)
    location /asset/v1/ {
        proxy_pass http://localhost:21080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
